include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    prefer_single_quotes: true
    prefer_final_locals: true
    prefer_final_fields: true
    unnecessary_const: true
    unnecessary_new: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true