name: lead_cart
description: "Modern e-commerce platform for LEAD College of Management"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_riverpod: ^2.4.9
  go_router: ^13.2.5
  supabase_flutter: ^2.5.6
  animate_do: ^3.3.4
  lottie: ^3.1.2
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  flutter_animate: ^4.5.0
  card_swiper: ^3.0.1
  animated_text_kit: ^4.2.2
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  photo_view: ^0.14.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  uuid: ^4.4.0
  intl: ^0.19.0
  fluttertoast: ^8.2.4
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  dio: ^5.4.3+1
  connectivity_plus: ^6.0.3
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^17.2.1+2
  url_launcher: ^6.2.5
  share_plus: ^9.0.0
  path_provider: ^2.1.3
  email_validator: ^2.1.17
  fl_chart: ^0.68.0
  timeago: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
