name: lead_kart

description: A production-ready Flutter e-commerce app with Supabase backend.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  
  # Backend & API
  supabase_flutter: ^2.9.1
  http: ^1.2.1
  
  # Image Storage & Upload
  cloudinary_public: 0.23.1
  image_picker: ^1.0.7
  cached_network_image: ^3.4.1
  
  # UI & Design
  shimmer: ^3.0.0
  lottie: ^3.3.1
  
  # Utils
  intl: ^0.20.2
  uuid: ^4.3.3
  url_launcher: ^6.3.1
  
  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/ 